export const DISABLE_DIALOG = "SIDE_PANEL:DISABLE_DIALOG";
export const ENABLE_DIALOG = "SIDE_PANEL:ENABLE_DIALOG";
export const DISABLE_PRIMARY_SIDE_PANEL =
  "SIDE_PANEL:DISABLE_PRIMARY_SIDE_PANEL";
export const ENABLE_PRIMARY_SIDE_PANEL = "SIDE_PANEL:ENABLE_PRIMARY_SIDE_PANEL";
export const DISABLE_SECONDARY_SIDE_PANEL =
  "SIDE_PANEL:DISABLE_SECONDARY_SIDE_PANEL";
export const ENABLE_SECONDARY_SIDE_PANEL =
  "SIDE_PANEL:ENABLE_SECONDARY_SIDE_PANEL";
export const SET_ACTIVE_BUTTON_ID = "SIDE_PANEL:SET_ACTIVE_BUTTON_ID";

//export const disabledDialog= () => ({ type: HAS_CLICKED });
